#!/bin/bash

# Deploy Trade Nexus to Development Environment
# This script deploys both backend and frontend to development

set -e  # Exit on error

echo "======================================"
echo "Trade Nexus - Development Deployment"
echo "======================================"
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if we're on develop branch or a feature branch
CURRENT_BRANCH=$(git branch --show-current)
if [[ "$CURRENT_BRANCH" != "develop" && ! "$CURRENT_BRANCH" =~ ^feature/.* ]]; then
    echo -e "${YELLOW}Warning: You're on branch '$CURRENT_BRANCH'.${NC}"
    echo "Development deployments should typically be from 'develop' or 'feature/*' branches."
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Check for uncommitted changes
if [[ -n $(git status -s) ]]; then
    echo -e "${YELLOW}Warning: You have uncommitted changes.${NC}"
    read -p "Continue with deployment? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

echo -e "${BLUE}Step 1: Deploying Backend (Cloudflare Workers)${NC}"
echo "--------------------------------------"
cd backend
echo "Running database migrations..."
wrangler d1 migrations apply trade-nexus-db-dev --env dev

echo "Deploying worker to development..."
wrangler deploy --env dev

WORKER_URL="https://trade-nexus-api-dev.metabilityllc1.workers.dev"
echo -e "${GREEN}✓ Backend deployed to: $WORKER_URL${NC}"
echo ""

cd ..

echo -e "${BLUE}Step 2: Deploying Frontend (Cloudflare Pages)${NC}"
echo "--------------------------------------"
cd frontend

# Update environment variable for dev backend
export NEXT_PUBLIC_API_URL="$WORKER_URL"
echo "Using API URL: $NEXT_PUBLIC_API_URL"

echo "Building frontend..."
npm run build

echo "Deploying to Cloudflare Pages (preview)..."
wrangler pages deploy out --project-name=trade-nexus-frontend --branch=dev

echo -e "${GREEN}✓ Frontend deployed to preview${NC}"
echo ""

cd ..

echo ""
echo -e "${GREEN}======================================"
echo "   Development Deployment Complete!"
echo "======================================${NC}"
echo ""
echo "Backend API: $WORKER_URL"
echo "Frontend: Check Cloudflare Pages dashboard for preview URL"
echo ""
echo -e "${YELLOW}Note: Preview URLs are automatically generated by Cloudflare Pages${NC}"
echo "Visit: https://dash.cloudflare.com/pages to view your deployment"
echo ""
